name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt install build-essential libgl1-mesa-dev mesa-common-dev libsdl2-dev libpoco-dev

      - name: Get libprojectM
        run: git clone --depth 1 https://github.com/projectM-visualizer/projectm.git
      - name: Build libprojectM
        run: |
          cd projectm
          mkdir build
          cd build
          cmake ..
          make -j4

      - name: Install projectM
        run: cd projectm/build && sudo make install

      - name: Build frontend-sdl2
        run: |
          mkdir build
          cd build
          cmake ..
          make -j4
