name: Build

on: [ push, pull_request ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: [ windows-latest, ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt install build-essential libgl1-mesa-dev mesa-common-dev libsdl2-dev

      - name: Get libprojectM
        run: git clone --depth 1 https://github.com/projectM-visualizer/projectm.git
      - run: |
          cd projectm
          mkdir build
          cd build
          cmake ..
          make -j4

      - run: cd projectm/build && sudo make install

      - name: CMake
        run: |
          mkdir build
          cd build
          cmake ..
          make -j4
